version: '3.8'

# ---------------------------------------------------------------------------------------------------- #
# Networks
# ---------------------------------------------------------------------------------------------------- #
networks:
  # ---------------------------------------------------------------------------------------------------- #
  # Default network
  # ---------------------------------------------------------------------------------------------------- #
  stack-postgresql:
    driver: bridge

# ---------------------------------------------------------------------------------------------------- #
# Services
# ---------------------------------------------------------------------------------------------------- #
services:
  # ---------------------------------------------------------------------------------------------------- #
  # Database PostgreSQL Service
  # ---------------------------------------------------------------------------------------------------- #
  db-service-postgresql:
    image: postgres:16.2-bullseye
    container_name: ${CTN_PFX:-err}postgresql
    restart: unless-stopped
    env_file:
      - ./postgresql/config/.env
    ports:
      - ${DB_PGSQL_EXT_PORT:-5432}:5432 # External Port to access the database with tools like DBeaver
    networks:
      - default
      - stack-postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

  # ---------------------------------------------------------------------------------------------------- #
  # Database Adminer Service
  # ---------------------------------------------------------------------------------------------------- #
  db-service-adminer:
    image: adminer:latest
    container_name: ${CTN_PFX:-err}adminer
    restart: unless-stopped
    ports:
      - ${ADM_PORT:-err}:8080
    env_file:
      - ./adminer/config/.env
    networks:
      - stack-postgresql

volumes:
  # ---------------------------------------------------------------------------------------------------- #
  # PostgreSQL Data Volume
  # ---------------------------------------------------------------------------------------------------- #
  postgresql-data-volume:
    driver: local
