########################################################################################################
# IMPORTANT NOTE: This file is the main Docker Compose configuration file for the project,
# It is used to define the services and the network configuration for the project, it defines
# the build context for the services and the target image to be built.
########################################################################################################

# Set the project name
name: auth-squared

# ---------------------------------------------------------------------------------------------------- #
# Networks
# ---------------------------------------------------------------------------------------------------- #
networks:
  # ---------------------------------------------------------------------------------------------------- #
  # Default network for the project
  # ---------------------------------------------------------------------------------------------------- #
  default:
    driver: bridge

# ---------------------------------------------------------------------------------------------------- #
# Volumes
# ---------------------------------------------------------------------------------------------------- #
volumes:
  # ---------------------------------------------------------------------------------------------------- #
  # Virtual environment volume
  # ---------------------------------------------------------------------------------------------------- #
  venv-virtual-volume:
    driver: local

  # ---------------------------------------------------------------------------------------------------- #
  # Workspace volume, for development only (share the codebase between the host and the containers)
  # ---------------------------------------------------------------------------------------------------- #
  workspace-physical-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./

  # ---------------------------------------------------------------------------------------------------- #
  # App codebase volume
  # ---------------------------------------------------------------------------------------------------- #
  app-physical-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./resources

# ---------------------------------------------------------------------------------------------------- #
# Services
# ---------------------------------------------------------------------------------------------------- #
services:
  # ---------------------------------------------------------------------------------------------------- #
  # Development service container (for development only, not for production)
  # ---------------------------------------------------------------------------------------------------- #
  app-service-dev:
    image: prm:dev-local
    build:
      context: .
      dockerfile: .docker/build-app/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
    user: ${UID:-1000}
    container_name: ${CTN_PFX:-err}dev
    restart: unless-stopped
    env_file:
      - .docker/build-app/config/.env
    volumes:
      # ? Mount the zshrc file to the container to use the same configuration
      - .devcontainer/config/.zshrc:/home/app-runner/.zshrc:rw
      # ? Mount the virtual environment into a volume to share it between the containers
      - venv-virtual-volume:/home/app-runner/app/resources/.venv:rw
      # ? Mount the workspace into a volume to share it between the host and the container
      - workspace-physical-volume:/home/app-runner/app:rw
    networks:
      - default

  # ---------------------------------------------------------------------------------------------------- #
  # API service container
  # ---------------------------------------------------------------------------------------------------- #
  app-service-api:
    image: prm:dev-runtime
    build:
      context: .
      dockerfile: .docker/build-app/Dockerfile
      target: runtime
      args:
        UID: ${UID:-1000}
    user: ${UID:-1000}
    container_name: ${CTN_PFX:-err}api
    restart: unless-stopped
    depends_on:
      app-service-dev:
        condition: service_started
      db-service-postgresql:
        condition: service_healthy
      cache-service-redis:
        condition: service_healthy
    env_file:
      - .docker/build-app/config/.env
    volumes:
      # ? Mount the virtual environment into a volume to share it between the containers
      - venv-virtual-volume:/home/app-runner/app/resources/.venv:rw
      # ? Mount the workspace into a volume to share it between the host and the container
      - app-physical-volume:/home/app-runner/app/resources:rw
    ports:
      - ${APP_PORT:-err}:80
    networks:
      - default

# ---------------------------------------------------------------------------------------------------- #
# Include other services here
# ---------------------------------------------------------------------------------------------------- #
include:
  - .docker/stack-supervision/compose.yml
  - .docker/stack-postgresql/compose.yml
  - .docker/stack-redis/compose.yml
