version: '3.8'

# Set the project name
name: auth-squared

# ---------------------------------------------------------------------------------------------------- #
# Networks
# ---------------------------------------------------------------------------------------------------- #
networks:
  # ---------------------------------------------------------------------------------------------------- #
  # Default network
  # ---------------------------------------------------------------------------------------------------- #
  default:
    driver: bridge

# ---------------------------------------------------------------------------------------------------- #
# Volumes
# ---------------------------------------------------------------------------------------------------- #
volumes:
  # ---------------------------------------------------------------------------------------------------- #
  # Virtual environment volume
  # ---------------------------------------------------------------------------------------------------- #
  venv-virtual-volume:
    driver: local

  # ---------------------------------------------------------------------------------------------------- #
  # Workspace volume, for development only (share the codebase between the host and the containers)
  # ---------------------------------------------------------------------------------------------------- #
  workspace-physical-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./

  # ---------------------------------------------------------------------------------------------------- #
  # App codebase volume
  # ---------------------------------------------------------------------------------------------------- #
  app-physical-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./resources

# ---------------------------------------------------------------------------------------------------- #
# Services
# ---------------------------------------------------------------------------------------------------- #
services:
  # ---------------------------------------------------------------------------------------------------- #
  # Development service container (for development only, not for production)
  # ---------------------------------------------------------------------------------------------------- #
  app-service-dev:
    image: authsq:dev-local
    build:
      context: .
      dockerfile: .docker/build-app/Dockerfile
      target: development
      args:
        PRJ_NAME: auth-squared
        UID: ${UID:-1000}
    user: ${UID:-1000}
    container_name: ${CTN_PFX:-err}dev
    restart: unless-stopped
    env_file:
      - .docker/build-app/config/.env
    volumes:
      - venv-virtual-volume:/opt/.venv:rw
      - workspace-physical-volume:/home/app-runner/workspace:rw
    networks:
      - default

  # ---------------------------------------------------------------------------------------------------- #
  # API service container
  # ---------------------------------------------------------------------------------------------------- #
  app-service-api:
    image: authsq:dev-runtime
    build:
      context: .
      dockerfile: .docker/build-app/Dockerfile
      target: runtime
      args:
        PRJ_NAME: auth-squared
        UID: ${UID:-1000}
    user: ${UID:-1000}
    container_name: ${CTN_PFX:-err}api
    restart: unless-stopped
    env_file:
      - .docker/build-app/config/.env
    volumes:
      - venv-virtual-volume:/opt/.venv:rw
      - app-physical-volume:/home/app-runner/apps/auth-squared:rw
    ports:
      - ${APP_PORT:-err}:80
    networks:
      - default

# ---------------------------------------------------------------------------------------------------- #
# Include other services here
# ---------------------------------------------------------------------------------------------------- #
include:
  - .docker/stack-supervision/docker-compose.yml
  - .docker/stack-postgresql/docker-compose.yml
  - .docker/stack-redis/docker-compose.yml
