name: C.C.C.C. (Conventional Commits Compliance Check)

on:
  push:
  pull_request:

jobs:
  cccc:
    name: C.C.C.C. (Conventional Commits Compliance Check)
    if: |
      ${{ !contains(github.event.pull_request.title, 'chore(release): :bookmark: update changelog') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Conventional Commits Compliance
        uses: cocogitto/cocogitto-action@v3.6
        with:
          check-latest-tag-only: true
